/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#262626",
        "tertiary": "#ffe792",
        "surface-tint": "#3fff8b",
        "primary": "#3fff8b",
        "on-tertiary-fixed": "#453900",
        "on-secondary-fixed-variant": "#00567f",
        "on-secondary-fixed": "#003855",
        "primary-container": "#13ea79",
        "on-surface-variant": "#adaaaa",
        "on-secondary": "#002a42",
        "on-background": "#ffffff",
        "secondary-container": "#006493",
        "secondary-fixed-dim": "#86cbff",
        "on-error-container": "#ffa8a3",
        "surface-container-lowest": "#000000",
        "surface-container": "#1a1919",
        "outline-variant": "#494847",
        "tertiary-fixed": "#ffd709",
        "secondary-dim": "#00a7f2",
        "error": "#ff716c",
        "primary-dim": "#24f07e",
        "on-surface": "#ffffff",
        "on-primary-fixed": "#004820",
        "surface-container-high": "#201f1f",
        "outline": "#777575",
        "inverse-on-surface": "#565554",
        "on-primary": "#005d2c",
        "surface-container-low": "#131313",
        "surface-container-highest": "#262626",
        "background": "#0e0e0e",
        "tertiary-container": "#ffd709",
        "on-primary-fixed-variant": "#006832",
        "surface": "#0e0e0e",
        "primary-fixed": "#3fff8b",
        "on-primary-container": "#004f24",
        "inverse-primary": "#006e35",
        "error-container": "#9f0519",
        "on-tertiary": "#655400",
        "inverse-surface": "#fcf8f8",
        "tertiary-dim": "#efc900",
        "error-dim": "#d7383b",
        "on-tertiary-container": "#5b4b00",
        "secondary": "#00affe",
        "primary-fixed-dim": "#24f07e",
        "tertiary-fixed-dim": "#efc900",
        "on-secondary-container": "#f3f8ff",
        "on-error": "#490006",
        "secondary-fixed": "#a7d7ff",
        "on-tertiary-fixed-variant": "#665500",
        "surface-bright": "#2c2c2c",
        "surface-dim": "#0e0e0e",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
